CREATE TABLE Customer(
	cid			BIGINT			PRIMARY KEY AUTO_INCREMENT,
	email		VARCHAR(20)		NOT NULL,
	passwd		VARCHAR(60)		NOT NULL,
	name		VARCHAR(20)		NOT NULL,
	ssn			VARCHAR(14)		NOT NULL,
	phone		VARCHAR(13) 	NOT NULL,
	regDate		TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP
)AUTO_INCREMENT = 1001;

SELECT * FROM Customer
SELECT count(*) FROM Customer
UPDATE Customer SET ssn = "123456-1234567"

CREATE TABLE Account (
	aid				BIGINT			PRIMARY KEY AUTO_INCREMENT,
	customerId		BIGINT			NOT NULL,
	accountNUM		CHAR(11)			NOT NULL, -- 000-00-0000
	accType			CHAR(1)			NOT NULL DEFAULT 'S',
	balance			DOUBLE			NOT NULL DEFAULT 0,
	interestRate	DOUBLE			NOT NULL DEFAULT 0.0,
	overAmount		DOUBLE			NOT NULL DEFAULT 0.0,
	regDate			TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	CONSTRAINT Account_customerId_FK
		FOREIGN KEY (customerId) REFERENCES Customer(cid)
)AUTO_INCREMENT = 3001;

DROP TABLE Account
DROP TABLE Customer

SELECT * FROM Customer;

CREATE TABLE Customer(
	userId		VARCHAR(20)		PRIMARY KEY,
	passwd		VARCHAR(60)		NOT NULL,
	name		VARCHAR(20)		NOT NULL,
	ssn			VARCHAR(14)		NOT NULL,
	phone		VARCHAR(13) 	NOT NULL
)

SELECT * FROM Account
UPDATE Account set balance = 10000 WHERE customerId = 'lty';
CREATE TABLE Account (
	aid				BIGINT			PRIMARY KEY AUTO_INCREMENT,
	customerId		VARCHAR(20)		NOT NULL,
	accountNUM		CHAR(11)		NOT NULL, -- 000-00-0000
	accType			CHAR(1)			NOT NULL DEFAULT 'S',
	balance			DOUBLE			NOT NULL DEFAULT 0,
	interestRate	DOUBLE			NOT NULL DEFAULT 0.0,
	overAmount		DOUBLE			NOT NULL DEFAULT 0.0,
	
	CONSTRAINT Account_customerId_FK
		FOREIGN KEY (customerId) REFERENCES Customer(userId)
)AUTO_INCREMENT = 3001;